// autogenerated code

package main

import "testing"
import "gflow"
import "regexp"

var tests = []testing.InternalTest{
	testing.InternalTest{"gflow.TestIT", gflow.TestIT},
}

var benchmarks = []testing.InternalBenchmark{}

func main() {
	testing.Main(regexp.MatchString, tests, benchmarks)
}
